# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body2(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, mes: str=None, cantidad: int=None):
        """
        Body2 - a model defined in Swagger

        :param mes: The mes of this Body2.
        :type mes: str
        :param cantidad: The cantidad of this Body2.
        :type cantidad: int
        """
        self.swagger_types = {
            'mes': str,
            'cantidad': int
        }

        self.attribute_map = {
            'mes': 'Mes',
            'cantidad': 'Cantidad'
        }

        self._mes = mes
        self._cantidad = cantidad

    @classmethod
    def from_dict(cls, dikt) -> 'Body2':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body2 of this Body2.
        :rtype: Body2
        """
        return deserialize_model(dikt, cls)

    @property
    def mes(self) -> str:
        """
        Gets the mes of this Body2.

        :return: The mes of this Body2.
        :rtype: str
        """
        return self._mes

    @mes.setter
    def mes(self, mes: str):
        """
        Sets the mes of this Body2.

        :param mes: The mes of this Body2.
        :type mes: str
        """

        self._mes = mes

    @property
    def cantidad(self) -> int:
        """
        Gets the cantidad of this Body2.

        :return: The cantidad of this Body2.
        :rtype: int
        """
        return self._cantidad

    @cantidad.setter
    def cantidad(self, cantidad: int):
        """
        Sets the cantidad of this Body2.

        :param cantidad: The cantidad of this Body2.
        :type cantidad: int
        """

        self._cantidad = cantidad

